
CREATE TABLE message (
  id bigint generated by default as identity primary key,
  sender text,
  send_time text,
  content text,
  channel_id text,
  channel_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table message enable row level security;

create policy "message are public." on message for
    select using (true);

create policy "Individuals can create message." on message for
    insert with check (true);

create policy "Individuals can update their own message." on message for
    update using (true);

create policy "Individuals can delete their own message." on message for
    delete using (true);

-- # test table
CREATE TABLE test_message (
  id bigint generated by default as identity primary key,
  sender text,
  send_time text,
  content text,
  channel_id text,
  channel_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table test_message enable row level security;

create policy "test_message are public." on test_message for
    select using (true);

create policy "Individuals can create test_message." on test_message for
    insert with check (true);

create policy "Individuals can update their own test_message." on test_message for
    update using (true);

create policy "Individuals can delete their own test_message." on test_message for
    delete using (true);


-- # dev table

CREATE TABLE dev_message (
  id bigint generated by default as identity primary key,
  sender text,
  send_time text,
  content text,
  channel_id text,
  channel_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table dev_message enable row level security;

create policy "dev_message are public." on dev_message for
    select using (true);

create policy "Individuals can create dev_message." on dev_message for
    insert with check (true);

create policy "Individuals can update their own dev_message." on dev_message for
    update using (true);

create policy "Individuals can delete their own dev_message." on dev_message for
    delete using (true);
